### ISSUE TITLE
What is the purpose of the kcas_test package?

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-multicore/kcas#45]
See question in https://github.com/ocaml/opam-repository/pull/23634

**Comment by polytypic** [comment]
Tests in this project depend on either `kcas`, or both `kcas` and `kcas_data`. Tests are placed into the `kcas_test` package that depends on both `kcas` and `kcas_data` so that the tests can be built. I got the idea to arrange things like this from [an opam issue](https://github.com/ocaml/dune/issues/3267#issuecomment-882384126).  Perhaps there is a better way?

**Comment by kit-ty-kate** [comment]
> I got the idea to arrange things like this from [an opam issue](https://github.com/ocaml/dune/issues/3267#issuecomment-882384126). Perhaps there is a better way?

You mean dune issue?

> Tests in this project depend on either `kcas`, or both `kcas` and `kcas_data`. Tests are placed into the `kcas_test` package that depends on both `kcas` and `kcas_data` so that the tests can be built (on CI).

I don't really understand that. If it depends on both kcas and kcas_data, then why not just make it a kcas_data test? (given one depend on the other)

**Comment by kit-ty-kate** [comment]
> Thinking about this further, suppose there would be three packages `kcas`,`kcas_data -> kcas`, and, say, `kcas_extras -> kcas` (arrow meaning depends). If I then wanted to have a test that would use both `kcas_data` and `kcas_extras`, I couldn't just place the tests into either one of the packages, AFAICS. Would having a `kcas_test -> kcas_data, kcas_extras` package then be the recommended approach or is there some other good way to have such tests then be run on opam's CI also?

Mmh, i still fail to see why this would be needed. Tests are usually testing one specific feature associated with a specific package so said test should probably be in the associated package. For example if you're testing `kcas_data` but for whatever reason need `kcas_extras` you can always add `kcas_extras` as a test dependency in the `kcas_data` package.

The only thing that makes it potentially require a separate package is if you're testing `kcas_extras` and really need `kcas_data`. But usually those cases where the dependencies cycle like that is usually a sign that something is wrong in the way the packages are defined (it most likely mean they are usually both used at the same time and it would make more sense to combine them into one single package).

My point is that requiring an extra test package should be very rare and not become the default way of doing things. opam-repository already has enough unneeded packages that have been added because people didn't know about subpackages (e.g. the tezos-*/octez-* packages) and adding even more is not sustainable (we're already hitting the "i can't update opam anymore because my file-system doesn't have enough inodes" kind of problem: e.g. https://github.com/ocaml/opam/issues/5484)

**Comment by kit-ty-kate** [comment]
Even looking at `kcas_data` it could've been `kcas.data` instead of creating a separate package it looks like, to me.

**Comment by polytypic** [comment]
Thanks! I made a new [PR](https://github.com/ocaml/opam-repository/pull/23642) to `opam-repository`, dropping the `kcas_test` package, and with the tests placed into either `kcas` or `kcas_data`.

---

Hmm... I think we are digressing here, but I'll add a few comments, sorry!

> Tests are usually testing one specific feature associated with a specific package [...]

My experience is that it is very important to also test at higher granularities (integration, end-to-end, ...), because those kinds of tests tend to reveal problems that don't even come to mind when unit testing isolated pieces of functionality.

The algorithms and data structures in `kcas` (and `kcas_data`) are stateful and concurrent.  It is not at all difficult to make bugs that only manifest themselves when you exercise multiple things together and/or concurrently.

On the topic of testing...

If testing one specific thing at a time is the gold standard, then why is opam running [_massive_ amounts of "revdeps" tests](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/a186ed021dbdd8f0a3d404268ebe1e67d58573a2)?

Don't get me entirely wrong here.  I think it is valuable to test things.  But why encourage packages to only use unit tests while opam itself performs massive amounts of rudimentary integration testing.

On the other hand, I'm not entirely convinced that opam should be running tests in the first place (which is kind of the root cause here).  I think testing that packages are installable is reasonable.  But running the test suites of packages... I'm not immediately convinced that the package manager CI should be doing that.  It is a valuable thing, but it also adds a _centralized_ choke point and a lot of friction.  In many other package managers it is the _distributed_ responsibility of package authors to test their stuff.  I would expect this has been discussed before somewhere.  I haven't seen/read those discussions and it is not really in my immediate interest to spend time on this at this point.  (And, yes, it would be possible to just define the `kcas` and `kcas_data` packages without tests.)

> requiring an extra test package should be very rare [...] add `kcas_extras` as a test dependency in the `kcas_data` package

Yes, I agree that having an extra test package is a hack.

Requiring packages as test dependencies sounds like a more reasonable way to have tests that span multiple packages. 👍 

> Even looking at `kcas_data` it could've been `kcas.data` instead of creating a separate package it looks like, to me.

The idea is that `kcas` is the core package that is entirely usable on its own and should ideally become essentially functionally complete at some point soonish.

The `kcas_data` package, OTOH, is entirely optional, more open ended, and would ideally get contributions in the form of new data structure implementations over time.

So, while it would be possible to just merge the two, and it might even be that most things using `kcas` would also use `kcas_data`, I wouldn't (for the above mentioned differences).

> [...] "i can't update opam anymore because my file-system doesn't have enough inodes"

Well, that is an architectural choice made in opam that could very well be questioned.  Using a git repository hosted at GitHub as a database does come with inherent scalability problems.  On quick glance, it seems `opam-repository` currently has about 30k files under `packages`.  Many other package managers/repositories do not have such technical limitations and host literally _millions_ of packages (Google tells me that maven central repository has "10,985,119 indexed packages" and that npm passed the millionth package milestone in 2019).  Again, I expect this has been discussed before and it is not in my immediate interest spend time on this.

----

With the above issues expressed, I definitely do appreciate the work and care that `opam-repository` maintainers do and exhibit.  Thanks!
