### ISSUE TITLE
[Question] Hashtable rehashing example

### ISSUE THREAD

**Issue by sidkshatriya** [ocaml-multicore/kcas#58]
Thank for the excellently written README. I am trying to understand the material in it.

I have a question related to Hashtable with rehashing:
> After switching to the rehashing state, all mutators will then cooperatively race to perform the rehash.

In what sense is the race cooperative? I agree that another mutator does not attempt to replace a (key, value) and thus cause a transaction failure for the mutator that is trying to do the more long running rehash but how you would then explain this as a cooperative race?

Also would this be an place where it might actually be a good idea to throw a `Later` exception if a rehash is pending? Why have multiple threads potentially all try to do a rehash? Why not let one thread do the rehash while other threads abort until the rehash is complete?

**Comment by polytypic** [comment]
> In what sense is the race cooperative? I agree that another mutator does not attempt to replace a (key, value) and thus cause a transaction failure for the mutator that is trying to do the more long running rehash but how you would then explain this as a cooperative race?

I would say that the race is cooperative, because everyone is racing to do the same thing and no one is prevented from working towards the same goal and then advance to their own goals.  All for one and and for all.  In that example rehashing is not cooperative in the sense that the operation would be divided into steps and everyone would be able to incrementally advance the operation one step at a time or by even taking those steps in parallel.

The approach I used in the current implementation of `Kcas_data.Hashtbl` [can also be cooperative in that sense](https://github.com/ocaml-multicore/kcas/blob/45fb899fb82c195486b5548f5d7056f020353ecc/src/kcas_data/hashtbl.ml#L168-L217) as long as the participants haven't tried to access the hash table earlier in their transactions.  It is not parallelized, but that should actually be relatively easy to implement.

However, speaking of rehashing, in particular, I believe an even better approach could be to perform rehashing lazily.  Basically, the array of buckets would be doubled and the locations of added buckets would be initialized to a special `Rehash` value.  Rehashing of a bucket would then take place whenever an access hits a bucket with the `Rehash` value.  Note that when the number of buckets is doubled or halved that amounts to adding or removing one bit of the hash.  So, a single rehash basically just partitions (or merges) the assoc list based on that bit.  (That is just the basic idea.  There are details to figure out.)

> Also would this be an place where it might actually be a good idea to throw a Later exception if a rehash is pending? Why have multiple threads potentially all try to do a rehash? Why not let one thread do the rehash while other threads abort until the rehash is complete?

That is also possible.  The hash table example was written before blocking support was added.  Now that kcas can block, it should also be possible to use a blocking approach.  Basically, the accessor that first sees the pending rehash would modify a location to say "I'm working on it".  Then other domains would block until that location is changed.

However, such a blocking approach is, by definition, not lock-free.  So, if the domain working on the rehash is not making progress, then everyone will be prevented from accessing the hash table.

**Comment by sidkshatriya** [comment]
Thanks for your detailed response and interesting food for thought !

> However, such a blocking approach is, by definition, not lock-free.

I don't think we promised that we would not block anywhere in the README text. Currently the situation is that each thread of execution will independently (and not incrementally) try to rehash. Only one thread of execution will reach completion while the work of others will be thrown away as they all try to rehash their snapshot of the hashtable.

> So, if the domain working on the rehash is not making progress, then everyone will be prevented from accessing the hash table.

If we restricted rehashing only to one domain there would be no reason why it would fail to make progress because it is the *only one* making the transaction on that location (others are being aborted) so the transaction should always succeed?

In fact, if many domains try to do rehashing completely it is more likely that something would go wrong with torn reads for instance and the whole system could fail to make progress?

So we have four options:
- Each domain tries to help with rehashing. This will complicate the algorithm for the README.
- (Current situation) Each domain tries to do rehashing independently. Leads to wasted CPU cycles as the work of all other domains except the race winner is thrown away. There could be a problem with torn reads as a huge number of locations in a potentially large Hashtable are attempted to be changed by many threads working on their own snapshots of the table.
- Lazy rehashing of some kind along the lines of what you explained. Again complicates the algorithm for the README.
- Throwing `Later` if the rehashing is already pending (Simplest especially for the README)

**Comment by polytypic** [comment]
> I don't think we promised that we would not block anywhere in the README text. 

It is a bit subtle, but a lock-free algorithm is a special case of a [non-blocking algorithm](https://en.wikipedia.org/wiki/Non-blocking_algorithm).  The paper [On the Nature of Progress](https://www.researchgate.net/publication/221039323_On_the_Nature_of_Progress) has more on the subject.  IOW, a lock-free hash table should, by definition, arrange things so that no thread is blocked waiting for another.

> Currently the situation is that each thread of execution will independently (and not incrementally) try to rehash. Only one thread of execution will reach completion while the work of others will be thrown away as they all try to rehash their snapshot of the hashtable.

Yes, assuming we are talking about the README example and multiple threads manage to see the pending rehash.  I would actually expect that in many cases rehashes happen quickly enough that most threads do not get a chance to notice any particular rehash. (In the `Kcas_data.Hashtbl` implementation rehashing is likely to happen more incrementally.)

That is how non-blocking algorithms often work.  Threads will either complete or roll back the work started by others.  In this case the former.  The benefit of this is that nobody is blocked waiting for another.

A single rehash doesn't necessarily take a lot of time.  In an unlucky case the OS might decide to switch out the thread performing rehashing.  During that time other threads, that could otherwise make progress, will be blocked and no thread is making progress.  With a fair scheduler that typically isn't a problem (as explained in the paper).

> In fact, if many domains try to do rehashing completely it is more likely that something would go wrong with torn reads for instance and the whole system could fail to make progress?

Well, in order for a thread to encounter a torn read, or just have their transaction become invalid due to outside changes to shared memory locations, some other thread must be making progress.  Transactions are invisible to each other until they actually succeed in committing their changes to memory.

"something would go wrong" sounds a bit scary. 😅 

So, what could go wrong?  Well, some thread could complete the rehash and commit the changes to shared memory.  In that case the transactions in other threads will either be aborted (by the periodic validation) or they will finish the rehash in their own transaction log and fail during the attempt to commit the log.  The transactions in other threads will then be retried and at that point the rehash has already been done (it is like they never saw it happening) and they will continue to attempt their own operations.

Not that scary. 😌

> So we have four options:

Yes, there are several approach with different tradeoffs and progress properties.

In the context of a specific application one can generally choose from a wider set of algorithms with different progress properties.  In particular, for many application blocking will be just fine.  For some applications it might be essential that an algorithm is wait-free or at the very least lock-free.  Eio, for example, [specifically uses lock-free algorithms](https://github.com/ocaml-multicore/eio/issues/382), because it wants to support special applications where blocking is not allowed.

Note that the [Race to cooperate](https://github.com/ocaml-multicore/kcas/tree/45fb899fb82c195486b5548f5d7056f020353ecc#race-to-cooperate) section in the README discusses an advanced technique where we intentionally (in spirit, but not technically) break the invisibility of transactions and communicate by performing more than a single transaction so that the threads can then cooperate.

But, yes, if you mean to say that it could be useful to have several (perhaps simpler) hash table variations as examples so that their properties could then be discussed, then yes, that could be nice. 👌 

Thinking a bit further, I think it would probably make sense to soon start breaking the README into multiple documents.  The main document would introduce the basics and link to other documents that could then spend more time discussing advanced techniques.

If you'd like to explore different kinds of hash table implementations using **kcas**, I'd be happy to review your work on them.

**Comment by sidkshatriya** [comment]
Thank you so much for spending the time here and on discuss.ocaml.org answering my (and other people's questions). I'll try not to trouble you more :-). 

Your reply makes a lot of sense and has convinced me that the current implementation of the Hashtable in the README is fine, especially since it mainly for teaching purposes.
